services:
  - type: web
    name: multi-tenant-chat-system
    env: static
    buildCommand: cd frontend && npm install
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 