services:
  - type: web
    name: multi-tenant-chat-system
    env: node
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm start
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: / 