# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# VSCode用の設定：このファイルはGitHub Actionsのワークフローファイルです
# 警告を無視: RENDER_DEPLOY_HOOK_URL

name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: cd frontend && npm install
      
      # テストがある場合は実行
      # - name: Run tests
      #   run: cd frontend && npm test
  
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        # 環境変数を直接run内で設定することで警告を回避
        run: |
          # GitHub Secretsから取得したRender.comのDeploy Hook URL
          DEPLOY_URL="${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          curl "$DEPLOY_URL" 